# Индивидулаьное задание

### *Условие*. Вариант 8
Соседями элемента Aj в матрице назовем элементы Ak с *i - 1 < k < i + 1*, *j - 1 < 1 < j + 1*, *(k, 1)/(i, j)*. Операция сглаживания матрицы дает новую матрицу того же размера, каждый элемент которой получается как среднее арифметическое имеющихся соседей соответствующего элемента исходной матрицы. Построить результат сглаживания заданной вещественной матрицы размером 7 на 7. В сглаженной матрице найти сумму модулей элементов, расположенных ниже главной диагонали.

In [73]:
import numpy as np

matrix = np.random.randint(-20,10,(7,7))
print("Сгенерированная матрица: ")
print(matrix)

sglaj_matrix = np.zeros((7,7))

Сгенерированная матрица: 
[[  0 -15   0 -12 -12   2 -16]
 [ -9 -15   0 -20   1  -8 -13]
 [ -9   6   2 -19   4 -11 -10]
 [  4  -3  -2   9 -12 -20  -9]
 [-11   6 -10   1   8 -16   8]
 [  4   2   6  -4  -2  -6 -11]
 [  7   9 -16  -5  -3 -14  -2]]


In [74]:
# Проверка на крайние нулевые столбцы и строки для корректного среза
for (i,j), element in np.ndenumerate(matrix):
    if i == 0 and j == 0:
        m = matrix[0:i+2, 0:j+2]
        rez = (np.sum(m) - element)/(m.size - 1)

    elif i == 0 and j != 0:
        m = matrix[0:i+2, j-1:j+2]
        rez = (np.sum(m) - element)/(m.size - 1)

    elif j == 0 and i != 0:
        m = matrix[i-1:i+2, 0:j+2]
        rez = (np.sum(m) - element)/(m.size - 1)

    else:
        m = matrix[i-1:i+2, j-1:j+2]
        rez = (np.sum(m) - element)/(m.size - 1)
    
    sglaj_matrix[i,j] = round(rez,2)

print("Сглаженная матрица:\n", sglaj_matrix)

Сглаженная матрица:
 [[-13.    -4.8  -12.4   -6.2   -7.4   -9.6   -6.33]
 [ -6.6   -3.12  -9.12  -4.5   -9.5   -6.88  -8.6 ]
 [ -3.4   -4.    -5.5   -2.25 -10.    -8.38 -12.2 ]
 [ -2.2   -1.75  -1.    -3.5   -5.5   -4.75  -9.8 ]
 [  2.6   -1.25   1.88  -0.88  -6.25  -5.5  -12.4 ]
 [  2.6   -0.62  -2.12  -2.62  -4.88  -4.    -6.  ]
 [  5.     0.6    1.6   -3.8   -6.2   -4.8  -10.33]]


In [75]:
print("Сглаженная матрица с обнуленными значениями по главной диагонали и выше:\n", np.tril(task_matrix, -1))
print("\nСумма модулей элементов, расположенных ниже главной диагонали: ", np.absolute(np.sum(task_matrix_null)))

Сглаженная матрица с обнуленными значениями по главной диагонали и выше:
 [[  0.     0.     0.     0.     0.     0.     0.  ]
 [ -1.4    0.     0.     0.     0.     0.     0.  ]
 [ -4.8   -9.12   0.     0.     0.     0.     0.  ]
 [-10.   -11.25 -11.38   0.     0.     0.     0.  ]
 [-15.   -11.62 -10.5  -10.38   0.     0.     0.  ]
 [-11.    -8.25 -12.12  -7.88  -6.25   0.     0.  ]
 [-14.    -2.8   -8.6   -3.4   -8.6   -7.2    0.  ]]

Сумма модулей элементов, расположенных ниже главной диагонали:  179.41
